// Generated by Wrangler by running `wrangler types`

interface Env {
	SUPABASE_URL: "https://ugolhjlcupimbzagfbgr.supabase.co";
	SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnb2xoamxjdXBpbWJ6YWdmYmdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjgxNjMwNDMsImV4cCI6MjA0MzczOTA0M30.k6Ju48rCFw50-nPRUIGd6IhV1SGLWVSdxTEn6AXVF3s";
}
